language: go

go:
- 1.7.4

services:
- mysql

script:
- go build main.go
- sudo ./main
- go test ./gostuff

sudo: true

before_install:
- bash ./_travis/data/travis-install-mysql-5.7.sh
- mysql --version
- pwd
- cd ./_travis/data
- openssl aes-256-cbc -K $encrypted_bec7680ae95b_key -iv $encrypted_bec7680ae95b_iv
  -in travis.tar.enc -out travis.tar -d
- tar xvf travis.tar
- bash ./importTravisTemplate.sh
- bash ./importTravisTables.sh
- cd ../../