language: go

go:
- 1.9

services:
- mysql

env:
- GOCHESSENV=travis

sudo: true
dist: trusty

before_install:
- go get github.com/sclevine/agouti 
- sudo apt-get update
- bash ./_travis/data/travis-install-mysql-5.7.sh
- mysql --version
- pwd
- cd ./_travis/data
- openssl aes-256-cbc -K $encrypted_bec7680ae95b_key -iv $encrypted_bec7680ae95b_iv
  -in travis.tar.enc -out travis.tar -d
- tar xvf travis.tar
- bash ./importTravisTemplate.sh
- bash ./importTravisTables.sh
- cd ../../

script:
- go build main.go
- sudo ./main &
- go test ./testing
- go test ./_travis
- wget http://chromedriver.storage.googleapis.com/2.37/chromedriver_linux64.zip
- sudo unzip chromedriver_linux64.zip -d /usr/lib/chromium-browser/
- "export PATH=$PATH:/usr/lib/chromium-browser/"
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 
- go test ./_webtest