language: go
go:
- 1.7.4
services:
- mysql
script:
- go test ./gostuff
- go test ./_travis

before_install:
- openssl aes-256-cbc -K $encrypted_bec7680ae95b_key -iv $encrypted_bec7680ae95b_iv
  -in ./_travis/data/travis.tar.enc -out ./_travis/data/travis.tar -d
- tar xvf ./_travis/data/travis.tar -C ./_travis/data
- bash ./_travis/data/importTravisTemplate.sh
- bash ./_travis/data/importTravisTables.sh