language: go
go:
- 1.7.4
services:
- mysql
script:
- go test ./gostuff
- go test ./_travis
before_install:
- mysql -e 'CREATE DATABASE IF NOT EXISTS gochess;'

dd:
- openssl aes-256-cbc -K $encrypted_19d459116927_key -iv $encrypted_19d459116927_iv
  -in importTravisTemplate.sh.enc -out importTravisTemplate.sh -d
- openssl aes-256-cbc -K $encrypted_19d459116927_key -iv $encrypted_19d459116927_iv
  -in importTravisTables.sh.enc -out importTravisTables.sh -d
- openssl aes-256-cbc -K $encrypted_19d459116927_key -iv $encrypted_19d459116927_iv
  -in gochessTemplate.sql.enc -out gochessTemplate.sql -d
