language: go
go:
- 1.7.4
services:
- mysql
script:
- go test ./gostuff
- go test ./_travis

before_install:
- openssl aes-256-cbc -K $encrypted_19d459116927_key -iv $encrypted_19d459116927_iv
  -in ./_travis/data/importTravisTemplate.sh.enc -out ./_travis/data/importTravisTemplate.sh -d
- openssl aes-256-cbc -K $encrypted_19d459116927_key -iv $encrypted_19d459116927_iv
  -in ./_travis/data/importTravisTables.sh.enc -out ./_travis/data/importTravisTables.sh -d
- openssl aes-256-cbc -K $encrypted_19d459116927_key -iv $encrypted_19d459116927_iv
  -in ./_travis/data/gochessTemplate.sql.enc -out ./_travis/data/gochessTemplate.sql -d
- mysql -e 'CREATE DATABASE IF NOT EXISTS gochess;'
- bash ./_travis/data/importTravisTemplate.sh
- bash ./_travis/data/importTravisTables.sh