language: go
go:
- 1.7.4
services:
- mysql
script:
- go test ./gostuff
- go test ./_travis

before_install:
- chmod +x ./_travis/data/*
- ./_travis/data/travis_mysql_5.7.sh
- ./_travis/data/mysql-reset-root-password.sh
- mysql --version
- pwd
- cd ./_travis/data
- openssl aes-256-cbc -K $encrypted_bec7680ae95b_key -iv $encrypted_bec7680ae95b_iv
  -in travis.tar.enc -out travis.tar -d
- tar xvf travis.tar
- bash ./importTravisTemplate.sh
- bash ./importTravisTables.sh