language: go

go:
- 1.8

services:
- mysql

env:
- GOCHESSENV=travis

sudo: true
dist: trusty

before_install:
- go get github.com/sclevine/agouti 
- sudo apt-get update
- bash ./_travis/data/travis-install-mysql-5.7.sh
- mysql --version
- pwd
- cd ./_travis/data
- openssl aes-256-cbc -K $encrypted_bec7680ae95b_key -iv $encrypted_bec7680ae95b_iv
  -in travis.tar.enc -out travis.tar -d
- tar xvf travis.tar
- bash ./importTravisTemplate.sh
- bash ./importTravisTables.sh
- cd ../../

script:
- go build main.go
- sudo ./main &
- go test ./testing
- go test ./_travis
- wget http://chromedriver.storage.googleapis.com/2.10/chromedriver_linux64.zip
- unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python2.7.9/
- export CHROME_BIN=chromium-browser
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- go test ./_webtest