language: go
go:
- 1.7.4
services:
- mysql
script:
- go test ./gostuff
- go test ./_travis
dd:
- openssl aes-256-cbc -K $encrypted_19d459116927_key -iv $encrypted_19d459116927_iv
  -in importTables.sh.enc -out importTables.sh -d
- openssl aes-256-cbc -K $encrypted_19d459116927_key -iv $encrypted_19d459116927_iv
  -in importTemplate.sh.enc -out importTemplate.sh -d
- openssl aes-256-cbc -K $encrypted_19d459116927_key -iv $encrypted_19d459116927_iv
  -in gochessTemplate.sql.enc -out gochessTemplate.sql -d
