language: go

go:
- 1.8

services:
- mysql

env:
- GOCHESSENV=travis

sudo: true

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
- wget http://chromedriver.storage.googleapis.com/2.27/chromedriver_linux64.zip
- unzip chromedriver_linux64.zip
- sudo apt-get install libnss3
- sudo apt-get --only-upgrade install google-chrome-stable
- sudo cp chromedriver /usr/local/bin/.
- sudo chmod +x /usr/local/bin/chromedriver
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- bash ./_travis/data/travis-install-mysql-5.7.sh
- mysql --version
- pwd
- cd ./_travis/data
- openssl aes-256-cbc -K $encrypted_bec7680ae95b_key -iv $encrypted_bec7680ae95b_iv
  -in travis.tar.enc -out travis.tar -d
- tar xvf travis.tar
- bash ./importTravisTemplate.sh
- bash ./importTravisTables.sh
- cd ../../

script:
- go build main.go
- sudo ./main &
- go test ./gostuff
- go test ./_travis
- "export PATH=$PATH:/usr/lib/chromium-browser/"
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- go test ./_webtest