version: "{build}"

# Operating system (build VM template)
os: Windows Server 2012 R2

clone_folder: c:\gopath\src\github.com\jonpchin\gochess
	
environment:
	GOPATH: c:\gopath
	GOVERSION: 1.7.4

services:
	- mysql

# scripts that run after cloning repository  
install:
	- set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
	- go version
	- go env
	- mkdir c:\gopath
	- go get -u github.com/go-sql-driver/mysql
	- go get -u github.com/dchest/captcha
	- go get -u github.com/fatih/color
	- go get -u golang.org/x/net/websocket
	- go get -u gopkg.in/gomail.v2
	- go get -u golang.org/x/crypto/scrypt
	- go get -u github.com/robfig/cron
	- go get -u github.com/disintegration/imaging
	- go get -u github.com/mholt/archiver
	- go get -u github.com/sclevine/agouti

build_script:
	- go build main.go
	- go test ./gostuff
	- go test ./_appveyor

# to disable deployment
deploy: off