version: "{build}"

# Operating system (build VM template)
os: Windows Server 2012 R2

clone_folder: c:\gopath\src\github.com\jonpchin\gochess
    
environment:
  GOPATH: c:\gopath
  GOVERSION: 1.7.4

services:
  - mysql
  
environment:
  gochess_decrypt:
    secure: yeEOqoy3DBRMeIA/10O3jA==

# scripts that run after cloning repository  
install:
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env
  - go get -t -v ./...
  - nuget install secure-file -ExcludeVersion
  - secure-file\tools\secure-file -decrypt _appveyor/data/gochessTemplate.sql.enc -secret %gochess_decrypt%
  - secure-file\tools\secure-file -decrypt _appveyor/data/importAppVeyorTables.sh.enc -secret %gochess_decrypt%
  - secure-file\tools\secure-file -decrypt _appveyor/data/importAppVeyorTemplate.sh.enc -secret %gochess_decrypt%
  - cd _appveyor\data
  - bash importAppVeyorTemplate.sh
  - bash importAppVeyorTables.sh
  - cd ../..

build_script:
  - go build main.go
  - go test ./gostuff
  - go test ./_appveyor

# to disable deployment
deploy: off