version: "{build}"

# Operating system (build VM template)
os: Windows Server 2012 R2

clone_folder: c:\gopath\src\github.com\jonpchin\gochess
    
environment:
  GOPATH: c:\gopath
  GOVERSION: 1.7.4

services:
  - mysql

# scripts that run after cloning repository  
install:
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env
  - go get -t -v ./...

build_script:
  - go build main.go
  - go test ./gostuff
  - go test ./_appveyor

# to disable deployment
deploy: off