version: "{build}"

# Operating system (build VM template)
os: Windows Server 2012 R2

clone_folder: c:\gopath\src\github.com\jonpchin\gochess
    
environment:
  GOPATH: c:\gopath
  GOVERSION: 1.10.1

# scripts that run after cloning repository  
install:
  - go version
  - go env
  - go get -t -v ./...

build_script:
  - go build
  - go test ./testing

# to disable deployment
deploy: off